version: "3"

services:
    zookeeper:
        #image: docker.io/bitnami/zookeeper:3.8
        image: docker.io/bitnami/zookeeper:latest
        ports:
            - "2181:2181"
        volumes:
            - "zookeeper_data:/bitnami"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        #image: docker.io/bitnami/kafka:3.4
        image: docker.io/bitnami/kafka:latest
        ports:
            - "9092:9092"
        volumes:
            - "kafka_data:/bitnami"
        environment:
            #- KAFKA_BROKER_ID=
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ENABLE_KRAFT=no
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.0.2.5:9092
        depends_on:
            - zookeeper

volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
